"""customize_chart — modify existing Plotly chart HTML without regenerating. No MCP imports."""

from __future__ import annotations

import base64
import json
import logging
import re
import struct
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[3]
_ADV = str(Path(__file__).resolve().parents[2] / "data_advanced")
for _p in (str(_ROOT), _ADV):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from shared.file_utils import atomic_write_text, resolve_path
from shared.progress import fail, info, ok

logger = logging.getLogger(__name__)


def _extract_plotly_json(html: str) -> tuple[str, str, str]:
    """Extract the Plotly call from the HTML. Returns (before, json_str, after)."""
    # Plotly.newPlot('id', data, layout, config)
    pattern = r"(Plotly\.newPlot\(\s*['\"][\w-]+['\"],\s*)(\[.*?\])(,\s*\{.*?\})(.*?\))"
    match = re.search(pattern, html, re.DOTALL)
    if not match:
        raise ValueError("Could not find Plotly.newPlot call in HTML. Not a valid Plotly chart HTML.")
    before = html[: match.start()]
    call_prefix = match.group(1)
    data_json = match.group(2)
    layout_json = match.group(3)
    after = html[match.end() :]
    return before, call_prefix, data_json, layout_json, after


def _extract_layout_json(html: str) -> tuple[dict, str, str, str, str]:
    """Parse layout dict from Plotly HTML, return (layout_dict, before, call_prefix, data_json, after)."""
    before, call_prefix, data_json, layout_part, after = _extract_plotly_json(html)
    # layout_part starts with ", {" — strip the leading comma+space
    layout_str = layout_part.lstrip(", ").strip()
    layout = json.loads(layout_str)
    return layout, before, call_prefix, data_json, layout_str, after


def _decode_plotly_y(y_field: object) -> list[float] | None:
    """Decode a trace's y values: either a plain list or Plotly's compact
    {"dtype": "f8", "bdata": <base64>} binary-encoded float64 array."""
    if isinstance(y_field, list):
        return list(y_field)
    if isinstance(y_field, dict) and "bdata" in y_field:
        raw = base64.b64decode(y_field["bdata"])
        n = len(raw) // 8
        return list(struct.unpack(f"<{n}d", raw))
    return None


def _encode_plotly_y(values: list[float], original_y_field: object) -> object:
    """Re-encode sorted y values, matching the original field's encoding."""
    if isinstance(original_y_field, dict) and "bdata" in original_y_field:
        raw = struct.pack(f"<{len(values)}d", *values)
        return {"dtype": original_y_field.get("dtype", "f8"), "bdata": base64.b64encode(raw).decode("ascii")}
    return values


def customize_chart(
    chart_path: str,
    title: str = "",
    x_label: str = "",
    y_label: str = "",
    color_scheme: list[str] = None,
    sort_bars: str = "",
    highlight: list[str] = None,
    annotations: list[dict] = None,
    show_value_labels: bool = False,
    width: int = 0,
    height: int = 0,
    output_path: str = "",
) -> dict:
    """Modify existing Plotly HTML chart. Changes title labels colors annotations."""
    progress = []
    try:
        path = resolve_path(chart_path)
        if not path.exists():
            return {
                "success": False,
                "error": f"Chart file not found: {path.name}",
                "hint": "Provide the path to an HTML chart file generated by generate_chart().",
                "progress": [fail("File not found", path.name)],
                "token_estimate": 20,
            }
        if path.suffix.lower() != ".html":
            return {
                "success": False,
                "error": "chart_path must be an HTML file.",
                "hint": "Only HTML files from generate_chart() or generate_dashboard() can be customized.",
                "progress": [fail("Wrong file type", path.suffix)],
                "token_estimate": 20,
            }

        html = path.read_text(encoding="utf-8")

        changes_applied: list[str] = []

        # Title replacement
        if title:
            # Try updating the <title> tag
            html = re.sub(r"<title>[^<]*</title>", f"<title>{title}</title>", html)
            # Try updating Plotly layout title
            html = re.sub(r'"title"\s*:\s*\{[^}]*"text"\s*:\s*"[^"]*"', f'"title": {{"text": "{title}"}}', html)
            changes_applied.append(f"title → '{title}'")
            progress.append(info("Title updated", title))

        # Axis labels
        if x_label:
            html = re.sub(
                r'"xaxis"\s*:\s*\{',
                f'"xaxis": {{"title": "{x_label}", ',
                html,
                count=1,
            )
            changes_applied.append(f"x-axis label → '{x_label}'")
            progress.append(info("X-axis label", x_label))

        if y_label:
            html = re.sub(
                r'"yaxis"\s*:\s*\{',
                f'"yaxis": {{"title": "{y_label}", ',
                html,
                count=1,
            )
            changes_applied.append(f"y-axis label → '{y_label}'")
            progress.append(info("Y-axis label", y_label))

        # Color scheme — replace marker.color arrays
        if color_scheme:
            colors_json = json.dumps(color_scheme)
            html = re.sub(
                r'"marker"\s*:\s*\{[^}]*"color"\s*:\s*"[^"]*"',
                f'"marker": {{"color": {colors_json[1:-1]}',
                html,
            )
            changes_applied.append(f"colors → {color_scheme[:3]}...")
            progress.append(info("Color scheme", str(color_scheme[:3])))

        # Sort bars / highlight specific bars — both operate on the parsed
        # trace data (categories + values), not raw text, since values may
        # be Plotly's base64-encoded binary float arrays.
        if sort_bars or highlight:
            try:
                _before, _call_prefix, _data_str, _layout_part, _after = _extract_plotly_json(html)
                traces = json.loads(_data_str)
                trace = traces[0]
                categories = trace["x"]
                if not isinstance(categories, list):
                    raise ValueError("trace has no categorical x values")
            except (ValueError, json.JSONDecodeError, KeyError, IndexError) as exc:
                return {
                    "success": False,
                    "error": f"Could not parse chart data: {exc}",
                    "hint": "sort_bars/highlight only work on single-trace bar charts from generate_chart().",
                    "progress": [fail("Chart data unparsable", str(exc))],
                    "token_estimate": 20,
                }

            if sort_bars:
                direction = sort_bars.lower()
                if direction not in ("asc", "desc"):
                    return {
                        "success": False,
                        "error": f"Invalid sort_bars value: {sort_bars}",
                        "hint": "Use 'asc' or 'desc'.",
                        "progress": [fail("Invalid sort_bars value", sort_bars)],
                        "token_estimate": 20,
                    }
                values = _decode_plotly_y(trace.get("y"))
                if values is None or len(values) != len(categories):
                    return {
                        "success": False,
                        "error": "Could not parse chart values for sorting.",
                        "hint": "sort_bars only works on single-trace bar charts from generate_chart().",
                        "progress": [fail("Chart values unparsable", "")],
                        "token_estimate": 20,
                    }
                order = sorted(range(len(categories)), key=lambda i: values[i], reverse=(direction == "desc"))
                categories = [categories[i] for i in order]
                trace["x"] = categories
                trace["y"] = _encode_plotly_y([values[i] for i in order], trace.get("y"))
                changes_applied.append(f"bars sorted {direction}")
                progress.append(info("Bars sorted", direction))

            if highlight:
                marker = trace.get("marker", {}) if isinstance(trace.get("marker"), dict) else {}
                base_color = marker.get("color") if isinstance(marker.get("color"), str) else "#636efa"
                highlight_set = {str(h) for h in highlight}
                marker["color"] = ["#EF553B" if str(c) in highlight_set else base_color for c in categories]
                trace["marker"] = marker
                changes_applied.append(f"{len(highlight)} categor{'y' if len(highlight) == 1 else 'ies'} highlighted")
                progress.append(info("Highlighted", str(highlight)))

            traces[0] = trace
            html = _before + _call_prefix + json.dumps(traces) + _layout_part + _after

        # Width / height
        if width or height:
            if width:
                html = re.sub(r'"width"\s*:\s*\d+', f'"width": {width}', html)
                changes_applied.append(f"width → {width}")
            if height:
                html = re.sub(r'"height"\s*:\s*\d+', f'"height": {height}', html)
                changes_applied.append(f"height → {height}")
            progress.append(info("Dimensions", f"{width or '?'}×{height or '?'}"))

        # Value labels (text mode for traces)
        if show_value_labels:
            html = html.replace('"textposition": "none"', '"textposition": "outside"')
            html = re.sub(r'"mode"\s*:\s*"lines"', '"mode": "lines+markers+text"', html)
            changes_applied.append("value labels → enabled")
            progress.append(info("Value labels", "enabled"))

        # Annotations
        if annotations:
            ann_list = []
            for ann in annotations:
                ann_list.append(
                    {
                        "x": ann.get("x", 0),
                        "y": ann.get("y", 0),
                        "text": ann.get("text", ""),
                        "showarrow": ann.get("showarrow", True),
                        "arrowhead": 2,
                        "font": {"size": 12},
                    }
                )
            ann_json = json.dumps(ann_list)
            # Inject or replace annotations in layout
            if '"annotations"' in html:
                html = re.sub(r'"annotations"\s*:\s*\[[^\]]*\]', f'"annotations": {ann_json}', html)
            else:
                html = re.sub(
                    r'"layout"\s*:\s*\{',
                    f'"layout": {{"annotations": {ann_json}, ',
                    html,
                    count=1,
                )
            changes_applied.append(f"{len(ann_list)} annotation(s) added")
            progress.append(info("Annotations", f"{len(ann_list)} added"))

        if not changes_applied:
            return {
                "success": False,
                "error": "No customization parameters provided.",
                "hint": "Provide at least one of: title, x_label, y_label, color_scheme, sort_bars, annotations, show_value_labels, width, height.",
                "progress": [fail("Nothing to change", "")],
                "token_estimate": 20,
            }

        if output_path:
            out_path = resolve_path(output_path)
        else:
            out_path = path.parent / f"{path.stem}_customized{path.suffix}"
        atomic_write_text(str(out_path), html)
        progress.append(ok("Chart customized", f"{len(changes_applied)} changes applied"))

        result = {
            "success": True,
            "op": "customize_chart",
            "input": path.name,
            "output_path": str(out_path),
            "changes_applied": changes_applied,
            "progress": progress,
        }
        result["token_estimate"] = len(str(result)) // 4
        return result

    except Exception as exc:
        logger.exception("customize_chart error")
        return {
            "success": False,
            "error": str(exc),
            "hint": "Ensure chart_path points to an HTML file from generate_chart() or generate_dashboard().",
            "progress": [fail("Unexpected error", str(exc))],
            "token_estimate": 20,
        }
