"""customize_chart — modify existing Plotly chart HTML without regenerating. No MCP imports."""

from __future__ import annotations

import json
import logging
import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[3]
_ADV = str(Path(__file__).resolve().parents[2] / "data_advanced")
for _p in (str(_ROOT), _ADV):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from shared.file_utils import atomic_write_text, resolve_path
from shared.progress import fail, info, ok

logger = logging.getLogger(__name__)


def _extract_plotly_json(html: str) -> tuple[str, str, str]:
    """Extract the Plotly call from the HTML. Returns (before, json_str, after)."""
    # Plotly.newPlot('id', data, layout, config)
    pattern = r"(Plotly\.newPlot\(['\"][\w-]+['\"],\s*)(\[.*?\])(,\s*\{.*?\})(.*?\))"
    match = re.search(pattern, html, re.DOTALL)
    if not match:
        raise ValueError("Could not find Plotly.newPlot call in HTML. Not a valid Plotly chart HTML.")
    before = html[: match.start()]
    call_prefix = match.group(1)
    data_json = match.group(2)
    layout_json = match.group(3)
    after = html[match.end() :]
    return before, call_prefix, data_json, layout_json, after


def _extract_layout_json(html: str) -> tuple[dict, str, str, str, str]:
    """Parse layout dict from Plotly HTML, return (layout_dict, before, call_prefix, data_json, after)."""
    before, call_prefix, data_json, layout_part, after = _extract_plotly_json(html)
    # layout_part starts with ", {" — strip the leading comma+space
    layout_str = layout_part.lstrip(", ").strip()
    layout = json.loads(layout_str)
    return layout, before, call_prefix, data_json, layout_str, after


def customize_chart(
    chart_path: str,
    title: str = "",
    x_label: str = "",
    y_label: str = "",
    color_scheme: list[str] = None,
    sort_bars: str = "",
    highlight: list[str] = None,
    annotations: list[dict] = None,
    show_value_labels: bool = False,
    width: int = 0,
    height: int = 0,
    output_path: str = "",
) -> dict:
    """Modify existing Plotly HTML chart. Changes title labels colors annotations."""
    progress = []
    try:
        path = resolve_path(chart_path)
        if not path.exists():
            return {
                "success": False,
                "error": f"Chart file not found: {path.name}",
                "hint": "Provide the path to an HTML chart file generated by generate_chart().",
                "progress": [fail("File not found", path.name)],
                "token_estimate": 20,
            }
        if path.suffix.lower() != ".html":
            return {
                "success": False,
                "error": "chart_path must be an HTML file.",
                "hint": "Only HTML files from generate_chart() or generate_dashboard() can be customized.",
                "progress": [fail("Wrong file type", path.suffix)],
                "token_estimate": 20,
            }

        html = path.read_text(encoding="utf-8")

        changes_applied: list[str] = []

        # Title replacement
        if title:
            # Try updating the <title> tag
            html = re.sub(r"<title>[^<]*</title>", f"<title>{title}</title>", html)
            # Try updating Plotly layout title
            html = re.sub(r'"title"\s*:\s*\{[^}]*"text"\s*:\s*"[^"]*"', f'"title": {{"text": "{title}"}}', html)
            changes_applied.append(f"title → '{title}'")
            progress.append(info("Title updated", title))

        # Axis labels
        if x_label:
            html = re.sub(
                r'"xaxis"\s*:\s*\{',
                f'"xaxis": {{"title": "{x_label}", ',
                html,
                count=1,
            )
            changes_applied.append(f"x-axis label → '{x_label}'")
            progress.append(info("X-axis label", x_label))

        if y_label:
            html = re.sub(
                r'"yaxis"\s*:\s*\{',
                f'"yaxis": {{"title": "{y_label}", ',
                html,
                count=1,
            )
            changes_applied.append(f"y-axis label → '{y_label}'")
            progress.append(info("Y-axis label", y_label))

        # Color scheme — replace marker.color arrays
        if color_scheme:
            colors_json = json.dumps(color_scheme)
            html = re.sub(
                r'"marker"\s*:\s*\{[^}]*"color"\s*:\s*"[^"]*"',
                f'"marker": {{"color": {colors_json[1:-1]}',
                html,
            )
            changes_applied.append(f"colors → {color_scheme[:3]}...")
            progress.append(info("Color scheme", str(color_scheme[:3])))

        # Width / height
        if width or height:
            if width:
                html = re.sub(r'"width"\s*:\s*\d+', f'"width": {width}', html)
                changes_applied.append(f"width → {width}")
            if height:
                html = re.sub(r'"height"\s*:\s*\d+', f'"height": {height}', html)
                changes_applied.append(f"height → {height}")
            progress.append(info("Dimensions", f"{width or '?'}×{height or '?'}"))

        # Value labels (text mode for traces)
        if show_value_labels:
            html = html.replace('"textposition": "none"', '"textposition": "outside"')
            html = re.sub(r'"mode"\s*:\s*"lines"', '"mode": "lines+markers+text"', html)
            changes_applied.append("value labels → enabled")
            progress.append(info("Value labels", "enabled"))

        # Annotations
        if annotations:
            ann_list = []
            for ann in annotations:
                ann_list.append(
                    {
                        "x": ann.get("x", 0),
                        "y": ann.get("y", 0),
                        "text": ann.get("text", ""),
                        "showarrow": ann.get("showarrow", True),
                        "arrowhead": 2,
                        "font": {"size": 12},
                    }
                )
            ann_json = json.dumps(ann_list)
            # Inject or replace annotations in layout
            if '"annotations"' in html:
                html = re.sub(r'"annotations"\s*:\s*\[[^\]]*\]', f'"annotations": {ann_json}', html)
            else:
                html = re.sub(
                    r'"layout"\s*:\s*\{',
                    f'"layout": {{"annotations": {ann_json}, ',
                    html,
                    count=1,
                )
            changes_applied.append(f"{len(ann_list)} annotation(s) added")
            progress.append(info("Annotations", f"{len(ann_list)} added"))

        if not changes_applied:
            return {
                "success": False,
                "error": "No customization parameters provided.",
                "hint": "Provide at least one of: title, x_label, y_label, color_scheme, sort_bars, annotations, show_value_labels, width, height.",
                "progress": [fail("Nothing to change", "")],
                "token_estimate": 20,
            }

        if output_path:
            out_path = resolve_path(output_path)
        else:
            out_path = path.parent / f"{path.stem}_customized{path.suffix}"
        atomic_write_text(str(out_path), html)
        progress.append(ok("Chart customized", f"{len(changes_applied)} changes applied"))

        result = {
            "success": True,
            "op": "customize_chart",
            "input": path.name,
            "output_path": str(out_path),
            "changes_applied": changes_applied,
            "progress": progress,
        }
        result["token_estimate"] = len(str(result)) // 4
        return result

    except Exception as exc:
        logger.exception("customize_chart error")
        return {
            "success": False,
            "error": str(exc),
            "hint": "Ensure chart_path points to an HTML file from generate_chart() or generate_dashboard().",
            "progress": [fail("Unexpected error", str(exc))],
            "token_estimate": 20,
        }
