"""customize_chart — modify existing Plotly chart HTML without regenerating. No MCP imports."""

from __future__ import annotations

import json
import logging
import re
import sys
from html import escape as html_escape
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[3]
_ADV = str(Path(__file__).resolve().parents[2] / "data_advanced")
for _p in (str(_ROOT), _ADV):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from shared.file_utils import atomic_write_text, embed_content, error_text, hint_for_error, resolve_path
from shared.plotly_payload import decode_array, encode_array, scan_balanced, split_newplot
from shared.progress import fail, info, ok, warn

logger = logging.getLogger(__name__)

_HIGHLIGHT_COLOR = "#EF553B"
_DEFAULT_TRACE_COLOR = "#636efa"


# The scanner and the array codec live in shared/plotly_payload.py: reading a
# figure back out of a generated page is needed in more than one place now, and
# two copies of a parser drift.
_scan_balanced = scan_balanced
_split_newplot = split_newplot
_decode_plotly_y = decode_array
_encode_plotly_y = encode_array


def _extract_plotly_json(html: str) -> tuple[str, str, str, str, str]:
    """Extract the Plotly call. Returns (before, call_prefix, data_json, layout_part, after).

    `layout_part` keeps its leading separator so the five pieces still concatenate
    back into the original document.
    """
    before, call_prefix, data_str, separator, layout_str, after = split_newplot(html)
    return before, call_prefix, data_str, separator + layout_str, after


def _title_dict(text: str) -> dict:
    return {"text": text}


# plotly reads a 3D figure's axis titles from layout.scene.xaxis, never from
# the top-level layout.xaxis, and a figure with no axes reads them from nowhere.
# Writing to the top level regardless put the label in the file -- where a grep
# for it succeeds -- and nothing on the screen.
_3D_TRACE_TYPES = frozenset({"scatter3d", "surface", "mesh3d", "cone", "streamtube", "volume", "isosurface"})
_AXISLESS_TRACE_TYPES = frozenset(
    {"pie", "sunburst", "treemap", "funnelarea", "icicle", "indicator", "sankey", "parcoords", "parcats"}
)


def _axis_home(traces: list, layout: dict) -> tuple[dict | None, str]:
    """Where this figure's axis titles have to go to be read.

    Returns the dict to write xaxis/yaxis into and a name for it, or
    (None, the trace types) when the figure has no axes to label.
    """
    types = {str(t.get("type", "")) for t in traces if isinstance(t, dict)}
    if types & _3D_TRACE_TYPES or isinstance(layout.get("scene"), dict):
        scene = layout.get("scene")
        if not isinstance(scene, dict):
            scene = {}
            layout["scene"] = scene
        return scene, "3D scene"
    if types and types <= _AXISLESS_TRACE_TYPES:
        return None, ", ".join(sorted(t for t in types if t))
    return layout, "cartesian"


def _apply_value_labels(trace: dict) -> None:
    """Turn on printed values for one trace, respecting its plot type."""
    trace["textposition"] = "outside" if trace.get("type") == "bar" else "top center"
    trace.setdefault("texttemplate", "%{y}")
    mode = trace.get("mode")
    if isinstance(mode, str) and "text" not in mode:
        trace["mode"] = f"{mode}+text"


def customize_chart(
    chart_path: str,
    title: str = "",
    x_label: str = "",
    y_label: str = "",
    color_scheme: list[str] = None,
    sort_bars: str = "",
    highlight: list[str] = None,
    annotations: list[dict] = None,
    show_value_labels: bool = False,
    width: int = 0,
    height: int = 0,
    output_path: str = "",
    return_content: bool = False,
) -> dict:
    """Modify existing Plotly HTML chart. Changes title labels colors annotations."""
    progress = []
    try:
        path = resolve_path(chart_path)
        if not path.exists():
            return {
                "success": False,
                "error": f"Chart file not found: {path.name}",
                "hint": "Provide the path to an HTML chart file generated by generate_chart().",
                "progress": [fail("File not found", path.name)],
                "token_estimate": 20,
            }
        if path.suffix.lower() != ".html":
            return {
                "success": False,
                "error": "chart_path must be an HTML file.",
                "hint": "Only HTML files from generate_chart() or generate_dashboard() can be customized.",
                "progress": [fail("Wrong file type", path.suffix)],
                "token_estimate": 20,
            }

        html = path.read_text(encoding="utf-8")

        # Every customization mutates the parsed trace/layout objects and the
        # document is re-serialised once at the end. Editing the JSON as text
        # silently produced unbalanced braces, so the chart parsed as valid HTML
        # but rendered as a blank page.
        try:
            before, call_prefix, data_str, separator, layout_str, after = _split_newplot(html)
            traces = json.loads(data_str)
            layout = json.loads(layout_str)
        except (ValueError, json.JSONDecodeError) as exc:
            return {
                "success": False,
                "error": f"Could not parse chart: {exc}",
                "hint": "Only HTML files from generate_chart() or generate_dashboard() can be customized.",
                "progress": [fail("Chart unparsable", str(exc))],
                "token_estimate": 20,
            }

        changes_applied: list[str] = []

        if title:
            # save_chart() hoists a figure's title into the page's <h1> and
            # clears it from the layout, so every other chart page carries its
            # caption once, as HTML. Writing the new title back into the layout
            # put it inside the SVG instead, where plotly centres it and never
            # wraps it -- at 390px wide a 52-character title overflowed its plot
            # by 34px at each end and was clipped mid-word. Worse, the page's
            # own <h1> still showed the title the chart was created with, so
            # customising the title left the reader looking at the old one with
            # the new one cut off inside the picture. The heading is the title.
            layout.pop("title", None)
            changes_applied.append(f"title → '{title}'")
            progress.append(info("Title updated", title))

        if x_label or y_label:
            home, kind = _axis_home(traces, layout)
            if home is None:
                # Saying "x-axis label → 'Spend'" about a pie chart is the same
                # lie as writing it to the wrong object: the caller is told a
                # change was applied and the picture does not have one.
                return {
                    "success": False,
                    "op": "customize_chart",
                    "error": f"A {kind} chart has no axes to label.",
                    "hint": (
                        "Drop x_label/y_label for this chart type, or set the axis titles when the "
                        "chart is built with generate_chart()."
                    ),
                    "progress": [*progress, fail("No axes to label", kind)],
                    "token_estimate": 30,
                }
            for key, label in (("xaxis", x_label), ("yaxis", y_label)):
                if not label:
                    continue
                axis = home.get(key)
                home[key] = axis if isinstance(axis, dict) else {}
                home[key]["title"] = _title_dict(label)
                changes_applied.append(f"{key[0]}-axis label → '{label}'")
                progress.append(info(f"{key[0].upper()}-axis label", f"{label} (on the {kind} axes)"))

        if sort_bars:
            direction = sort_bars.lower()
            if direction not in ("asc", "desc"):
                return {
                    "success": False,
                    "error": f"Invalid sort_bars value: {sort_bars}",
                    "hint": "Use 'asc' or 'desc'.",
                    "progress": [fail("Invalid sort_bars value", sort_bars)],
                    "token_estimate": 20,
                }

        if sort_bars or highlight:
            try:
                trace = traces[0]
                categories = trace["x"]
                if not isinstance(categories, list):
                    raise ValueError("trace has no categorical x values")
            except (KeyError, IndexError, TypeError, ValueError) as exc:
                return {
                    "success": False,
                    "error": f"Could not parse chart data: {exc}",
                    "hint": "sort_bars/highlight only work on single-trace bar charts from generate_chart().",
                    "progress": [fail("Chart data unparsable", str(exc))],
                    "token_estimate": 20,
                }

            if sort_bars:
                direction = sort_bars.lower()
                values = _decode_plotly_y(trace.get("y"))
                if values is None or len(values) != len(categories):
                    return {
                        "success": False,
                        "error": "Could not parse chart values for sorting.",
                        "hint": "sort_bars only works on single-trace bar charts from generate_chart().",
                        "progress": [fail("Chart values unparsable", "")],
                        "token_estimate": 20,
                    }
                order = sorted(range(len(categories)), key=lambda i: values[i], reverse=(direction == "desc"))
                categories = [categories[i] for i in order]
                trace["x"] = categories
                trace["y"] = _encode_plotly_y([values[i] for i in order], trace.get("y"))
                changes_applied.append(f"bars sorted {direction}")
                progress.append(info("Bars sorted", direction))

            if highlight:
                marker = trace.get("marker", {}) if isinstance(trace.get("marker"), dict) else {}
                base_color = marker.get("color") if isinstance(marker.get("color"), str) else _DEFAULT_TRACE_COLOR
                highlight_set = {str(h) for h in highlight}
                marker["color"] = [_HIGHLIGHT_COLOR if str(c) in highlight_set else base_color for c in categories]
                trace["marker"] = marker
                changes_applied.append(f"{len(highlight)} categor{'y' if len(highlight) == 1 else 'ies'} highlighted")
                progress.append(info("Highlighted", str(highlight)))

            traces[0] = trace

        if color_scheme:
            # Per-point colours for a single categorical trace, palette otherwise —
            # a bar chart wants one colour per bar, a multi-trace chart one per trace.
            first = traces[0] if traces else {}
            categories = first.get("x") if isinstance(first, dict) else None
            if len(traces) == 1 and isinstance(categories, list) and not highlight:
                marker = first.get("marker", {}) if isinstance(first.get("marker"), dict) else {}
                marker["color"] = [color_scheme[i % len(color_scheme)] for i in range(len(categories))]
                first["marker"] = marker
                traces[0] = first
            layout["colorway"] = list(color_scheme)
            changes_applied.append(f"colors → {color_scheme[:3]}...")
            progress.append(info("Color scheme", str(color_scheme[:3])))

        if width or height:
            if width:
                layout["width"] = width
                changes_applied.append(f"width → {width}")
            if height:
                layout["height"] = height
                changes_applied.append(f"height → {height}")
            progress.append(info("Dimensions", f"{width or '?'}×{height or '?'}"))

        if show_value_labels:
            for trace in traces:
                if isinstance(trace, dict):
                    _apply_value_labels(trace)
            changes_applied.append("value labels → enabled")
            progress.append(info("Value labels", "enabled"))

        if annotations:
            # An annotation arrives as a bare dict, so no schema layer can check
            # its keys: a caller who wrote {"label": "...", "value": 1250.5}
            # got {"x": 0, "y": 0, "text": ""} and the response said
            # "1 annotation(s) added". An empty label at the origin, reported as
            # a change applied. `label` is accepted as the alias it clearly is,
            # and an annotation with no text at all is refused by name rather
            # than drawn blank.
            _ALIASES = {"label": "text", "caption": "text", "note": "text"}
            built: list[dict] = []
            unknown_keys: set[str] = set()
            for index, ann in enumerate(annotations):
                if not isinstance(ann, dict):
                    return {
                        "success": False,
                        "op": "customize_chart",
                        "error": f"annotations[{index}] is {type(ann).__name__}, not an object.",
                        "hint": 'Each annotation is {"text": "...", "x": <x>, "y": <y>}.',
                        "progress": [*progress, fail("Invalid annotation", str(ann)[:60])],
                        "token_estimate": 30,
                    }
                normalised = {_ALIASES.get(k, k): v for k, v in ann.items()}
                unknown_keys |= {k for k in normalised if k not in {"x", "y", "text", "showarrow"}}
                text = str(normalised.get("text", "")).strip()
                if not text:
                    return {
                        "success": False,
                        "op": "customize_chart",
                        "error": (
                            f"annotations[{index}] has no text: got keys {sorted(ann)}. "
                            "An annotation with no text draws an empty label."
                        ),
                        "hint": 'Use {"text": "your label", "x": <x>, "y": <y>}; `label` is accepted for `text`.',
                        "progress": [*progress, fail("Annotation has no text", str(sorted(ann)))],
                        "token_estimate": 40,
                    }
                built.append(
                    {
                        "x": normalised.get("x", 0),
                        "y": normalised.get("y", 0),
                        "text": text,
                        "showarrow": normalised.get("showarrow", True),
                        "arrowhead": 2,
                        "font": {"size": 12},
                    }
                )
            layout["annotations"] = built
            if unknown_keys:
                progress.append(
                    warn(
                        "Unrecognised annotation keys ignored",
                        f"{sorted(unknown_keys)} — accepted: x, y, text, showarrow",
                    )
                )
            changes_applied.append(f"{len(built)} annotation(s) added")
            progress.append(info("Annotations", f"{len(built)} added"))

        if not changes_applied:
            return {
                "success": False,
                "error": "No customization parameters provided.",
                "hint": "Provide at least one of: title, x_label, y_label, color_scheme, sort_bars, annotations, show_value_labels, width, height.",
                "progress": [fail("Nothing to change", "")],
                "token_estimate": 20,
            }

        html = before + call_prefix + json.dumps(traces) + separator + json.dumps(layout) + after
        if title:
            # A lambda, not an f-string replacement: re.sub treats backslashes
            # and \1 in a replacement string as group references, so a title
            # containing either would corrupt the page or raise.
            safe = html_escape(title)
            html = re.sub(r"<title>[^<]*</title>", lambda _m: f"<title>{safe}</title>", html, count=1)
            # The visible caption, not just the browser tab. Only chart pages
            # built by chart_page_html carry this heading; anything else simply
            # does not match and keeps whatever markup it had.
            html = re.sub(
                r'(<h1 class="chart-title">)[^<]*(</h1>)',
                lambda m: f"{m.group(1)}{safe}{m.group(2)}",
                html,
                count=1,
            )

        # A chart that no longer parses is a blank page in the browser, and the
        # file would still look like valid HTML on disk. Fail loudly instead.
        try:
            _, _, check_data, _, check_layout, _ = _split_newplot(html)
            json.loads(check_data)
            json.loads(check_layout)
        except (ValueError, json.JSONDecodeError) as exc:  # pragma: no cover - defensive
            return {
                "success": False,
                "error": f"Customization produced an unrenderable chart: {exc}",
                "hint": "Report this chart_path — the source chart's payload could not be rewritten safely.",
                "progress": [fail("Output would not render", str(exc))],
                "token_estimate": 20,
            }

        if output_path:
            out_path = resolve_path(output_path)
        else:
            out_path = path.parent / f"{path.stem}_customized{path.suffix}"
        atomic_write_text(str(out_path), html)
        progress.append(ok("Chart customized", f"{len(changes_applied)} changes applied"))

        result = {
            "success": True,
            "op": "customize_chart",
            "input": path.name,
            "output_path": str(out_path),
            "changes_applied": changes_applied,
            "progress": progress,
        }
        embed_content(result, out_path, return_content)
        result["token_estimate"] = len(str(result)) // 4
        return result

    except Exception as exc:
        logger.exception("customize_chart error")
        return {
            "success": False,
            "error": error_text(exc),
            "hint": hint_for_error(
                exc, "Ensure chart_path points to an HTML file from generate_chart() or generate_dashboard()."
            ),
            "progress": [fail("Unexpected error", str(exc))],
            "token_estimate": 20,
        }
